import type { RaceContext } from "./types";

export const demoRaceCards: RaceContext[] = [
  {
    meetingId: "rosehill-2026-03-28",
    meetingName: "Rosehill Gardens",
    venue: "Rosehill",
    raceNumber: 7,
    startTime: "2026-03-28T16:35:00+10:00",
    distanceMeters: 1500,
    className: "BM88",
    trackCondition: "Soft 5",
    railPosition: "True",
    weather: "Fine, light northerly",
    runners: [
      {
        id: "r7-1",
        number: 1,
        name: "Vector Signal",
        barrier: 3,
        weightKg: 58.5,
        jockey: "J. McDonald",
        trainer: "C. Waller",
        runStyle: "on-pace",
        lastStartFinish: 2,
        daysSinceRun: 21,
        secondUp: true,
        signals: {
          speed: 1.28,
          pace: 0.92,
          finish: 0.54,
          class: 0.84,
          trackDistance: 0.71,
          jockeyTrainer: 1.1,
          formCycle: 0.76,
          stableIntent: 0.48,
          barrierTempo: 0.82,
          marketSupport: 0.65,
        },
        quotes: [
          { source: "betfair", decimalOdds: 4.6, commissionRate: 0.05 },
          { source: "corporate", decimalOdds: 4.4 },
          { source: "tote", decimalOdds: 4.2 },
        ],
        modelNotes: ["Strong second-up profile", "Maps one pair closer than main rivals"],
      },
      {
        id: "r7-2",
        number: 2,
        name: "Late Equation",
        barrier: 10,
        weightKg: 57,
        jockey: "T. Berry",
        trainer: "J. Pride",
        runStyle: "backmarker",
        lastStartFinish: 5,
        daysSinceRun: 14,
        signals: {
          speed: 0.74,
          pace: -0.55,
          finish: 1.32,
          class: 0.35,
          trackDistance: 0.66,
          jockeyTrainer: 0.31,
          formCycle: 0.28,
          stableIntent: 0.15,
          barrierTempo: -0.61,
          marketSupport: -0.22,
        },
        quotes: [
          { source: "betfair", decimalOdds: 9.8, commissionRate: 0.05 },
          { source: "corporate", decimalOdds: 9.0 },
          { source: "tote", decimalOdds: 8.4 },
        ],
        modelNotes: ["Needs genuine speed", "Draw hurts settling pattern"],
      },
      {
        id: "r7-3",
        number: 3,
        name: "Cross Margin",
        barrier: 6,
        weightKg: 56.5,
        jockey: "N. Rawiller",
        trainer: "A. Neasham",
        runStyle: "midfield",
        lastStartFinish: 1,
        daysSinceRun: 28,
        signals: {
          speed: 1.04,
          pace: 0.26,
          finish: 0.88,
          class: 0.77,
          trackDistance: 1.18,
          jockeyTrainer: 0.44,
          formCycle: 0.81,
          stableIntent: 0.52,
          barrierTempo: 0.36,
          marketSupport: 0.58,
        },
        quotes: [
          { source: "betfair", decimalOdds: 5.8, commissionRate: 0.05 },
          { source: "corporate", decimalOdds: 5.5 },
          { source: "tote", decimalOdds: 5.2 },
        ],
        modelNotes: ["Track and trip specialist", "Last-start figure held up strongly"],
      },
      {
        id: "r7-4",
        number: 4,
        name: "Bayesian Drift",
        barrier: 12,
        weightKg: 56,
        jockey: "R. Jones",
        trainer: "K. Lees",
        runStyle: "leader",
        lastStartFinish: 8,
        daysSinceRun: 35,
        firstUp: true,
        signals: {
          speed: 0.42,
          pace: 1.22,
          finish: -0.18,
          class: 0.12,
          trackDistance: 0.14,
          jockeyTrainer: -0.12,
          formCycle: -0.38,
          stableIntent: 0.33,
          barrierTempo: -0.44,
          marketSupport: -0.61,
        },
        quotes: [
          { source: "betfair", decimalOdds: 14.5, commissionRate: 0.05 },
          { source: "corporate", decimalOdds: 13 },
          { source: "tote", decimalOdds: 12.5 },
        ],
        modelNotes: ["Can overdo it from wide gate", "First-up fitness query"],
      },
      {
        id: "r7-5",
        number: 5,
        name: "Residual Value",
        barrier: 2,
        weightKg: 55.5,
        jockey: "T. Schiller",
        trainer: "M. Smith",
        runStyle: "midfield",
        lastStartFinish: 3,
        daysSinceRun: 17,
        signals: {
          speed: 0.96,
          pace: 0.38,
          finish: 0.72,
          class: 0.51,
          trackDistance: 0.68,
          jockeyTrainer: 0.27,
          formCycle: 0.57,
          stableIntent: 0.19,
          barrierTempo: 0.63,
          marketSupport: 0.41,
        },
        quotes: [
          { source: "betfair", decimalOdds: 7.6, commissionRate: 0.05 },
          { source: "corporate", decimalOdds: 7.2 },
          { source: "tote", decimalOdds: 6.9 },
        ],
        modelNotes: ["Inside draw improves tactical map", "Less upside than top two but underbet"],
      },
    ],
  },
];
